### ISSUE TITLE
__init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by i6t6** [GGGGeorge-gao/Lianjia_spider#1]
我是用的Python3.7，运行时控制台报错
`2020-07-30 20:31:00 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "D:\Anaconda\anacondas\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "D:\Anaconda\anacondas\lib\site-packages\scrapy\crawler.py", line 88, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
TypeError: __init__() got an unexpected keyword argument 'encoding'`
百度过后猜测应该是Python版本问题，传入了init()不需要的参数，不过没找到解决办法

**Comment by GGGGeorge-gao** [comment]
报错可以写具体一点吗，哪个爬虫，错误类型位置，还有报错的具体信息

**Comment by 291196945** [comment]
①运行Lianjia爬虫（那个遍历链家的搜索页中所有选项分类及筛选条件的所有页数URL的）②控制台输出`D:\Anaconda\anacondas\python.exe D:/1spider/lianjia_all/scrapy_redis_analise/Lianjia_spider/Lianjia_spider/launch_Lianjia.py
2020-07-30 20:41:50 [scrapy.utils.log] INFO: Scrapy 1.8.0 started (bot: Lianjia_spider)
2020-07-30 20:41:50 [scrapy.utils.log] INFO: Versions: lxml 4.4.1.0, libxml2 2.9.9, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1g  21 Apr 2020), cryptography 2.9.2, Platform Windows-10-10.0.18362-SP0
2020-07-30 20:41:50 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'Lianjia_spider', 'COMMANDS_MODULE': 'Lianjia_spider.command', 'DEPTH_LIMIT': 6, 'DUPEFILTER_CLASS': 'scrapy_redis.dupefilter.RFPDupeFilter', 'NEWSPIDER_MODULE': 'Lianjia_spider.spiders', 'SCHEDULER': 'scrapy_redis.scheduler.Scheduler', 'SPIDER_MODULES': ['Lianjia_spider.spiders'], 'USER_AGENT': 'Mozilla/5.0.html (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.html.648.133 Safari/534.16'}
2020-07-30 20:41:50 [scrapy.extensions.telnet] INFO: Telnet Password: e57bd65910ff4f71
2020-07-30 20:41:50 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2020-07-30 20:41:50 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-07-30 20:41:50 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-07-30 20:41:50 [scrapy.middleware] INFO: Enabled item pipelines:
['Lianjia_spider.pipelines.LianjiaSpiderPipeline']
2020-07-30 20:41:50 [scrapy.core.engine] INFO: Spider opened
Unhandled error in Deferred:
2020-07-30 20:41:50 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "D:\Anaconda\anacondas\lib\site-packages\scrapy\crawler.py", line 184, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "D:\Anaconda\anacondas\lib\site-packages\scrapy\crawler.py", line 188, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "D:\Anaconda\anacondas\lib\site-packages\twisted\internet\defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "D:\Anaconda\anacondas\lib\site-packages\twisted\internet\defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "D:\Anaconda\anacondas\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "D:\Anaconda\anacondas\lib\site-packages\scrapy\crawler.py", line 88, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
builtins.TypeError: __init__() got an unexpected keyword argument 'encoding'

2020-07-30 20:41:50 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "D:\Anaconda\anacondas\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "D:\Anaconda\anacondas\lib\site-packages\scrapy\crawler.py", line 88, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
TypeError: __init__() got an unexpected keyword argument 'encoding'
`

**Comment by GGGGeorge-gao** [comment]
我刚刚commit了项目的requirements，Scrapy版本是1.7.3，你的是1.8.0，建议降级一下试试看（应该是版本的问题
